title: Daniel S. Buckstein
description: I thoroughly enjoy graphics programming, animation programming, quaternions and other math-heavy things.
markdown: kramdown
kramdown: 
    math_engine: mathjax
    parse_block_html: true
exclude: 
    - node_modules
    - vendor/bundle/
    - vendor/cache/
    - vendor/gems/
    - vendor/ruby/
    - LICENSE
    - README.md
